#!/usr/bin/env node
const fs = require("fs");
const path = require("path");

function getHash() {
  return Math.random()
    .toString(36)
    .substr(2, 9);
}

function generateItem(_, index) {
  const random = Math.random();
  return {
    id: index,
    title: index,
    content: getHash().repeat(Math.round(random * 50 + 1)),
  };
}

function genList(count) {
  return Array.from({ length: count }, generateItem);
}

fs.writeFileSync(
  path.resolve(__dirname, "../src/assets/data.json"),
  JSON.stringify(genList(10000)),
);
